# Generated by Django 3.0.4 on 2020-05-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='FriendInfomation',
        ),
        migrations.RenameField(
            model_name='friendinfomation',
            old_name='title',
            new_name='name',
        ),
    ]
