# Generated by Django 3.0.4 on 2020-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20200527_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinfomation',
            name='name',
        ),
        migrations.AddField(
            model_name='friendinfomation',
            name='Birthday',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='friendinfomation',
            name='firstName',
            field=models.CharField(default=None, max_length=36),
        ),
        migrations.AddField(
            model_name='friendinfomation',
            name='is_Men',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='friendinfomation',
            name='lastName',
            field=models.CharField(default=None, max_length=36),
        ),
    ]
