# Generated by Django 3.0.4 on 2020-06-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_remove_friendinfomation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_friend',
            name='friend',
            field=models.ManyToManyField(to='Management.FriendInfomation'),
        ),
    ]
