# Generated by Django 3.0.4 on 2020-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20200604_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinfomation',
            name='Birthday',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
