# Generated by Django 3.0.4 on 2020-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_group_friend_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_friend',
            name='friend',
            field=models.ManyToManyField(related_name='groups', to='Management.FriendInfomation'),
        ),
    ]
