# Generated by Django 3.0.4 on 2020-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20200610_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_friend',
            old_name='friend',
            new_name='member',
        ),
    ]
